apiVersion: v1
kind: ConfigMap

metadata:
  name: ran-automation-config

data:
  ENVIRONMENT_NAME: "ENV-PRAGUE-01"
  PRB_THRESHOLD: "20"
  SINR_THRESHOLD: "5"
  RAN_ADAPTER_URL: "http://ran-automation-service:8000"