apiVersion: apps/v1
kind: Deployment

metadata:
  name: ran-automation

  labels:
    app: ran-automation

spec:
  replicas: 1

  selector:
    matchLabels:
      app: ran-automation

  template:
    metadata:
      labels:
        app: ran-automation

    spec:
      containers:
        - name: ran-automation

          image: ran-automation-resilience-lab:v2.3.1

          imagePullPolicy: IfNotPresent

          env:
            - name: APPLICATION_RELEASE
              value: "APP-v2.3.1"

            - name: OPTIMIZATION_INTERVAL_SECONDS
              value: "60"

          envFrom:
            - configMapRef:
                name: ran-automation-config

          ports:
            - containerPort: 8000

          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"

            limits:
              cpu: "500m"
              memory: "256Mi"

          readinessProbe:
            httpGet:
              path: /cells
              port: 8000

            initialDelaySeconds: 2
            periodSeconds: 5

          livenessProbe:
            tcpSocket:
              port: 8000

            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
